name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: POE2AffinityService
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Ensure Publish Directory Exists
      run: mkdir -p publish

    - name: Ensure CHANGELOG.md Exists
      shell: pwsh
      run: |
        if (-Not (Test-Path "CHANGELOG.md")) {
          New-Item -ItemType File -Path "CHANGELOG.md" -Value "# Changelog"
        }

    - name: Build Project using MSBuild
      run: msbuild /p:Configuration=Release /p:TargetFramework=net8.0 /p:RuntimeIdentifier=win-x64 /p:PublishDir=publish/cli /t:Publish
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: publish/POE2AffinityService.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
