name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: POE2AffinityService
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Ensure Publish Directory Exists
      run: mkdir -p publish

    - name: Ensure CHANGELOG.md Exists
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "# Changelog" > CHANGELOG.md
        fi

    - name: Build and Publish as Single File
      run: dotnet publish --configuration Release --self-contained --runtime win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishDir=publish

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: publish/POE2AffinityService.exe
        asset_name: POE2AffinityService.exe
        asset_content_type: application/octet-stream
